spring:
  application:
    name: carddemo-batch
  profiles:
    active: local
  batch:
    jdbc:
      initialize-schema: never
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081
