-- Repeatable migration: seed test users for auth-service
-- Generated by generate_seed_data.py

DELETE FROM user_security;

INSERT INTO user_security (usr_id, usr_fname, usr_lname, usr_pwd, usr_type) VALUES ('admin01', 'System', 'Admin', '$2a$10$N9qo8uLOickgx2ZMRZoMye.IjqQBi0eI7X.jMU0WG10XU8p.KEWKG', 'A');
INSERT INTO user_security (usr_id, usr_fname, usr_lname, usr_pwd, usr_type) VALUES ('user0001', 'Test', 'User', '$2a$10$N9qo8uLOickgx2ZMRZoMye.IjqQBi0eI7X.jMU0WG10XU8p.KEWKG', 'U');

