CREATE TABLE customers (
    cust_id            BIGINT       PRIMARY KEY,
    first_name         VARCHAR(25),
    middle_name        VARCHAR(25),
    last_name          VARCHAR(25),
    addr_line_1        VARCHAR(50),
    addr_line_2        VARCHAR(50),
    addr_line_3        VARCHAR(50),
    state_cd           VARCHAR(2),
    country_cd         VARCHAR(3),
    zip                VARCHAR(10),
    phone_1            VARCHAR(15),
    phone_2            VARCHAR(15),
    ssn                BIGINT,
    govt_issued_id     VARCHAR(20),
    dob                VARCHAR(10),
    eft_account_id     VARCHAR(10),
    pri_card_holder_ind VARCHAR(1),
    fico_credit_score  INT
);
