server:
  port: 8081

spring:
  application:
    name: carddemo-auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/carddemo?currentSchema=security
    username: carddemo
    password: carddemo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    schemas: security

jwt:
  secret: CardDemoSecretKeyForJWTTokenGenerationMustBeAtLeast256Bits!
  expiration-ms: 3600000
