CREATE TABLE IF NOT EXISTS customer (
    cust_id                  BIGINT       NOT NULL PRIMARY KEY,
    cust_first_name          VARCHAR(25),
    cust_middle_name         VARCHAR(25),
    cust_last_name           VARCHAR(25),
    cust_addr_line_1         VARCHAR(50),
    cust_addr_line_2         VARCHAR(50),
    cust_addr_line_3         VARCHAR(50),
    cust_addr_state_cd       CHAR(2),
    cust_addr_country_cd     CHAR(3),
    cust_addr_zip            VARCHAR(10),
    cust_phone_num_1         VARCHAR(15),
    cust_phone_num_2         VARCHAR(15),
    cust_ssn                 BIGINT,
    cust_govt_issued_id      VARCHAR(20),
    cust_dob                 DATE,
    cust_eft_account_id      VARCHAR(10),
    cust_pri_card_holder_ind CHAR(1),
    cust_fico_credit_score   INT
);
